/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List devices
         * @description The devices to offer. Found by local broadcast; if that finds nothing, by SiliconDust's cloud lookup (unless disabled); plus any devices configured by address. The cloud result is kept until a refresh.
         */
        get: operations["list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/antenna/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch every tuner of a device (event stream)
         * @description Server-Sent Events for aiming an antenna: an `antenna-mode-status` event about once a second, whose data is an array of `AntennaReading`, one per tuner in order.
         */
        get: operations["antenna_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/channelmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Each tuner's channel map
         * @description The channel map each tuner is set to on the device, which decides what a channel number such as `27` means when tuning. Read-only. Null for a tuner that does not answer or has a map this app does not know.
         */
        get: operations["channel_maps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device model and tuner count */
        get: operations["device_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/scan/{tuner}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan for channels
         * @description Scans a channel map on one tuner and returns the channels that locked, with their programs. This occupies the tuner and can take two minutes. Limited to 6 requests a minute per client.
         */
        get: operations["scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/stream/play.m3u": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * M3U playlist for a program
         * @description A one-entry playlist, sent as a download.
         */
        get: operations["playlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/stream/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * URL of a program
         * @description The URL a player can open to watch one program, by RF channel and program number, which avoids two stations sharing a virtual channel. Only devices on the current device list are served.
         */
        get: operations["stream_url"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/atsc3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tune an ATSC 3.0 channel
         * @description Builds `atsc3:<channel>[:<plp>+<plp>...]` from validated parts.
         */
        post: operations["set_atsc3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tune a channel */
        post: operations["set_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/channel/down": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Previous channel */
        post: operations["channel_down"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/channel/up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next channel */
        post: operations["channel_up"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the tuner */
        post: operations["clear_tuner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/l1info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ATSC 3.0 L1 signalling */
        get: operations["l1_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/plpinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ATSC 3.0 PLP details */
        get: operations["plp_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Programs on the tuned channel
         * @description Empty unless the tuner has a lock. Right after a channel change the device can need a few seconds, so this retries for up to about 7 seconds.
         */
        get: operations["programs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tuner status */
        get: operations["tuner_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/tuner/{tuner}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch a tuner (event stream)
         * @description Server-Sent Events: a `tuner-status` event about once a second, whose data is a `TunerEvent`. See the notes on event streams in the API description.
         */
        get: operations["tuner_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Frontend build version
         * @description Read by the page to find out whether a newer build is available.
         */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One tuner's reading inside an `antenna-mode-status` event. */
        AntennaReading: {
            status?: null | components["schemas"]["TunerStatus"];
            /** Format: int32 */
            tuner: number;
        };
        /** @description The body of `POST .../atsc3`. */
        Atsc3Request: {
            /**
             * @description The RF channel, as digits. A JSON number is accepted too.
             * @example 27
             */
            channel: string;
            /** @description The PLPs to decode, 0 to 255 each (up to 64). Each may also be a string of digits. */
            plps?: number[];
        };
        /** @description The body of `POST .../channel`. */
        ChannelRequest: {
            /**
             * @description What to tune: `27`, `auto:27`, `8vsb:27`, `qam256:117`, `auto:575000000`,
             *     `atsc3:27`, `atsc3:27:0+1+2`, or the special values `none` (stop), `+` and `-`
             *     (next and previous channel).
             * @example auto:27
             */
            channel: string;
        };
        /** @description A tuner device the user can pick. */
        Device: {
            /** @description What commands address the device by: a device ID, IP address or hostname. */
            id: string;
            ip: string;
            name: string;
            online: boolean;
        };
        /** @description Model and capabilities of one device. */
        DeviceInfo: {
            atsc3Support: boolean;
            model: string;
            /** Format: int32 */
            tuners: number;
        };
        /** @description The body of every error response. */
        ErrorBody: {
            /** @description What went wrong, in words. */
            error: string;
        };
        /** @description One ATSC 3.0 physical layer pipe, from `/tuner<n>/plpinfo`. */
        PlpInfo: {
            coderate?: string | null;
            layer?: string | null;
            lls?: boolean | null;
            lock?: boolean | null;
            modulation?: string | null;
            sfi?: string | null;
            timeInterleaving?: string | null;
        };
        /** @description One program (virtual channel) on the tuned channel. */
        Program: {
            atsc3: boolean;
            /** @description Same as `name`; kept for clients that read it. */
            callsign: string;
            encrypted: boolean;
            name: string;
            programNum: string;
            /** @description The parenthesised note after the name, e.g. `encrypted` or `atsc3`. */
            status: string;
            virtualChannel: string;
        };
        /** @description A program found during a channel scan. */
        ScanProgram: {
            name: string;
            programNum: string;
            virtualChannel: string;
        };
        /** @description A frequency that locked during a channel scan. */
        ScannedChannel: {
            channel: string;
            frequency: string;
            modulation: string;
            programs: components["schemas"]["ScanProgram"][];
            /** Format: int32 */
            signalStrength: number;
            /** Format: int32 */
            snr: number;
            /** Format: int32 */
            symbolQuality: number;
        };
        /** @description A URL a player can open. */
        StreamUrl: {
            /** @example http://192.168.1.50:5004/auto/ch34-3 */
            url: string;
        };
        /** @description The answer to a tuning command. */
        TuneResult: {
            /** @description What the device answered, usually empty. */
            result: string;
            success: boolean;
        };
        /**
         * @description The payload of a `tuner-status` event: the tuner's status, plus the current
         *     program and the ATSC 3.0 details.
         *
         *     A tuner that does not answer still produces an event, with none of the status
         *     fields (no `channel`, no `lock`), so a page can tell the device is not
         *     reporting. `plpInfo` and `l1Info` are only fetched while a channel is tuned.
         */
        TunerEvent: {
            /**
             * Format: int64
             * @description Stream bitrate in bits per second.
             */
            bps?: number | null;
            /** @description The tuned channel as the device reports it, e.g. `auto:34`, or `none`. */
            channel?: string | null;
            /** @description The selected program number, as the device reports it, or null. */
            currentProgram: string | null;
            /** @description The debug counters the dB estimates came from. */
            debugRaw?: string | null;
            /** @description ATSC 3.0 L1 signalling as raw key/value pairs, or null. */
            l1Info: {
                [key: string]: string;
            } | null;
            /** @description Whether the tuner has a lock on the signal. */
            lock?: boolean | null;
            /** @description ATSC 3.0 PLPs by id, or null when the device reports none. */
            plpInfo: {
                [key: string]: components["schemas"]["PlpInfo"];
            } | null;
            /**
             * Format: int64
             * @description Packets per second.
             */
            pps?: number | null;
            /**
             * Format: int64
             * @description Symbol error quality, percent.
             */
            seq?: number | null;
            /**
             * Format: int64
             * @description Signal-to-noise quality, percent.
             */
            snq?: number | null;
            /**
             * Format: double
             * @description Signal-to-noise estimated in dB, when the device reports the counters for it.
             */
            snrDb?: number | null;
            /**
             * Format: int64
             * @description Signal strength, percent.
             */
            ss?: number | null;
            /**
             * Format: double
             * @description Signal strength estimated in dBm, when the device reports the counters for it.
             */
            ssDb?: number | null;
        };
        /** @description One reading of `/tuner<n>/status`. */
        TunerStatus: {
            /**
             * Format: int64
             * @description Stream bitrate in bits per second.
             */
            bps?: number | null;
            /** @description The tuned channel as the device reports it, e.g. `8vsb:27`, or `none`. */
            channel?: string | null;
            /** @description The debug counters the dB estimates came from, as `signal-snr/third`. */
            debugRaw?: string | null;
            lock: boolean;
            /**
             * Format: int64
             * @description Packets per second.
             */
            pps?: number | null;
            /**
             * Format: int64
             * @description Symbol error quality, percent.
             */
            seq?: number | null;
            /**
             * Format: int64
             * @description Signal-to-noise quality, percent.
             */
            snq?: number | null;
            /**
             * Format: double
             * @description Signal-to-noise estimated in dB from the debug counters.
             */
            snrDb?: number | null;
            /**
             * Format: int64
             * @description Signal strength, percent.
             */
            ss?: number | null;
            /**
             * Format: double
             * @description Signal strength estimated in dBm from the debug counters.
             */
            ssDb?: number | null;
        };
        /** @description What the built frontend says about itself. */
        Version: {
            /** @description When it was built (ISO 8601), or null when unknown. */
            buildTime?: string | null;
            /** @description A hash of the build, or `unknown` when there is no build information. */
            hash: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices: {
        parameters: {
            query?: {
                /** @description `true` is the user pressing Refresh: it forgets remembered devices and allows the cloud lookup to run again. Any other value is ignored. */
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            /** @description Too many requests from this client. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    antenna_stream: {
        parameters: {
            query: {
                /** @description How many tuners to watch, 1 to 8 (plain digits). */
                tuners: number;
            };
            header?: never;
            path: {
                /** @description A device ID, IPv4 address or hostname. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream; each event is named `antenna-mode-status`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AntennaReading"][];
                };
            };
            /** @description A device or `tuners` is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description This client already holds the most streams it may. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    channel_maps: {
        parameters: {
            query: {
                /** @description How many tuners to read, 1 to 8 (plain digits). */
                tuners: number;
            };
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per tuner, in order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (string | null)[];
                };
            };
            /** @description A device or `tuners` is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    device_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The device. An unreachable one is reported as model `Unknown` with two tuners. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceInfo"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    scan: {
        parameters: {
            query?: {
                /** @description One of `us-bcast` (the default), `us-cable`, `us-hrc`, `us-irc`, `ca-bcast`, `ca-cable`, `ca-hrc`, `ca-irc`, `eu-bcast`, `eu-cable`, `au-bcast`, `au-cable`. Giving it twice is an error. */
                channelMap?: string;
            };
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The channels that locked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannedChannel"][];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests from this client. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    playlist: {
        parameters: {
            query: {
                /** @description The RF channel, as digits (1 to 10). */
                ch: string;
                /** @description The program number, as digits (1 to 10). */
                program: string;
                /** @description A label for the entry; control characters are removed and it is cut at 64 characters. */
                name?: string;
            };
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The playlist. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/x-mpegurl": string;
                };
            };
            /** @description `ch` or `program` is missing or not digits. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device is not on the list. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stream_url: {
        parameters: {
            query: {
                /** @description The RF channel, as digits (1 to 10). */
                ch: string;
                /** @description The program number, as digits (1 to 10). */
                program: string;
            };
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamUrl"];
                };
            };
            /** @description `ch` or `program` is missing or not digits. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device is not on the list. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_atsc3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Atsc3Request"];
            };
        };
        responses: {
            /** @description Tuned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuneResult"];
                };
            };
            /** @description The channel or the PLPs are not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        /** @description The channel must be a string; a JSON number is refused here (but accepted by the `atsc3` endpoint). */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelRequest"];
            };
        };
        responses: {
            /** @description Tuned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuneResult"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    channel_down: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tuned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuneResult"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    channel_up: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tuned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuneResult"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    clear_tuner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuneResult"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The device or the tool reported an error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    l1_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The raw key/value pairs, or null when the device reports none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    } | null;
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    plp_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PLPs by id, or null when the device reports none or has no ATSC 3.0 support. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["PlpInfo"];
                    } | null;
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    programs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The programs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"][];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    tuner_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID (e.g. `1080ABCD`), IPv4 address or hostname: letters, digits, dots and hyphens, starting with a letter or digit, at most 253 characters. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One reading, or null when the tuner did not answer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["TunerStatus"];
                };
            };
            /** @description A device, tuner or parameter is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    tuner_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A device ID, IPv4 address or hostname. */
                id: string;
                /** @description The tuner index, 0 to 7. */
                tuner: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream; each event is named `tuner-status`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TunerEvent"];
                };
            };
            /** @description A device or tuner is not valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description This client already holds the most streams it may. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
}
